[package]
name = "rarathon"
version = "0.0.1"
authors = [ "Dan Everton <dan@iocaine.org>" ]

[lib]
name = "rarathon"

[[bin]]
name = "marathon_client"
test = false
doc = false

[dependencies]
getopts = "*"
hyper = "*"
rustc-serialize = "*"
url = "*"

